<?php get_header(); ?>
<section class="content-page service-page"><div class="nb-wrap"><p class="eyebrow">Services</p><h1>Focused technology.<br><span class="hero-accent">Useful outcomes.</span></h1><p class="page-lead">We combine product thinking, web engineering and applied AI to build systems that fit the work—and remain yours.</p>
<div class="service-grid">
<?php $services=array(
array('php-nodejs','01 / APPLICATION DEVELOPMENT','PHP & Node.js','PHP for content, commerce, administration and transactional systems; Node.js for APIs, integrations and real-time workloads.',array('WordPress and Magento development','CakePHP for RAD; Laravel as an alternative','Node.js and TypeScript services','Relational data and application APIs')),
array('firebase','02 / MANAGED APPLICATION PLATFORM','Firebase','A Google Cloud-connected application stack for products that benefit from managed authentication, data, storage and hosting.',array('Firebase Authentication','Cloud Firestore or SQL Connect','Cloud Functions and application hosting','Usage and cost monitoring')),
array('ai','03 / AI IMPLEMENTATION','Applied AI','AI features built around a defined task, using managed platforms or focused model APIs according to the application requirements.',array('Retrieval-augmented generation','Document extraction and classification','Google, AWS, Groq and Fireworks integrations','Evaluation, permissions and monitoring')),
array('cloud','04 / INFRASTRUCTURE','Cloud Infrastructure','AWS or Google Cloud infrastructure sized for the application, with explicit decisions about compute, storage, networking and operations.',array('Application deployment','Managed databases and object storage','Backups, monitoring and access control','Scaling and cost review')));
foreach($services as $item): ?><article class="service-card" id="<?php echo esc_attr($item[0]); ?>"><span><?php echo esc_html($item[1]); ?></span><h2><?php echo esc_html($item[2]); ?></h2><p><?php echo esc_html($item[3]); ?></p><ul><?php foreach($item[4] as $point) echo '<li>'.esc_html($point).'</li>'; ?></ul><a class="service-link" href="<?php echo esc_url(home_url('/services/'.($item[0]==='ai'?'applied-ai':($item[0]==='cloud'?'cloud-infrastructure':$item[0])).'/')); ?>">View details →</a></article><?php endforeach; ?>
</div><div class="cta-panel"><div><p class="eyebrow">Start with the problem</p><h2>Tell us what should work better.</h2></div><div class="cta-actions"><a class="button button-primary" href="<?php echo esc_url(home_url('/contact/')); ?>">Start a conversation</a></div></div></div></section>
<?php get_footer(); ?>
