<?php get_header(); ?>
<section class="hero"><div class="hero__glow"></div><div class="shell hero__grid">
	<div class="hero__copy"><p class="eyebrow"><span></span>AI that earns its place</p><h1>From complex work to <em>clear advantage.</em></h1><p class="hero__lead">We design and build focused AI systems, automations and data products that improve how your business actually works.</p><div class="button-row"><a class="button" href="<?php echo esc_url( home_url( '/contact/' ) ); ?>">Discuss your challenge <span>↗</span></a><a class="text-link" href="<?php echo esc_url( home_url( '/services/' ) ); ?>">Explore our services <span>→</span></a></div><div class="hero__proof"><span>Strategy</span><span>Engineering</span><span>Delivery</span></div></div>
	<div class="system-card" aria-label="AI workflow illustration"><div class="system-card__top"><span class="status-dot"></span>System online <code>MAI/01</code></div><div class="signal"><div class="signal__core"><b>AI</b><small>ENGINE</small></div><i></i><i></i><i></i></div><div class="metric-grid"><div><small>INPUT</small><strong>Business data</strong></div><div><small>PROCESS</small><strong>Smart workflows</strong></div><div><small>OUTPUT</small><strong>Useful action</strong></div></div><div class="terminal"><span>01</span>Understand the work<br><span>02</span>Design the system<br><span>03</span>Measure the outcome <b>READY_</b></div></div>
</div></section>
<section class="trust-strip"><div class="shell"><p>One partner from first question to working system</p><div><span>◆ AI PRODUCTS</span><span>⌁ AUTOMATION</span><span>▦ DATA SYSTEMS</span><span>◎ ADVISORY</span></div></div></section>
<section class="section" id="about"><div class="shell"><div class="section-heading"><div><p class="eyebrow"><span></span>What we solve</p><h2>Technology shaped around the work—not the hype.</h2></div><p>AI creates value when it understands your context, fits your workflow and delivers a result people can trust.</p></div><div class="feature-grid">
	<article class="feature-card feature-card--wide"><span class="feature-card__number">01</span><div class="icon-box">⌁</div><h3>Operational automation</h3><p>Remove repetitive steps and connect fragmented tools with dependable, human-aware workflows.</p><a href="<?php echo esc_url( home_url( '/services/#automation' ) ); ?>">Learn more →</a><div class="mini-flow"><b>Trigger</b><i></i><b>Reason</b><i></i><b>Act</b></div></article>
	<article class="feature-card"><span class="feature-card__number">02</span><div class="icon-box">✦</div><h3>Applied AI products</h3><p>Purpose-built assistants, search and decision tools grounded in your information.</p><a href="<?php echo esc_url( home_url( '/services/#products' ) ); ?>">Learn more →</a></article>
	<article class="feature-card"><span class="feature-card__number">03</span><div class="icon-box">▦</div><h3>Data foundations</h3><p>Clean pipelines and structured knowledge that make intelligent systems reliable.</p><a href="<?php echo esc_url( home_url( '/services/#data' ) ); ?>">Learn more →</a></article>
</div></div></section>
<section class="section section--dark" id="process"><div class="shell"><div class="section-heading"><div><p class="eyebrow"><span></span>How we work</p><h2>Small steps. Working proof. Clear ownership.</h2></div><p>We reduce uncertainty early, ship in useful increments and leave you with a system you understand.</p></div><ol class="process"><li><b>01</b><h3>Discover</h3><p>Map the workflow, constraints and most valuable outcome.</p></li><li><b>02</b><h3>Prototype</h3><p>Test the core assumption with real users and data.</p></li><li><b>03</b><h3>Build</h3><p>Engineer, integrate and secure the production system.</p></li><li><b>04</b><h3>Improve</h3><p>Measure quality and evolve what creates value.</p></li></ol></div></section>
<section class="cta-section"><div class="shell cta-panel"><div><p class="eyebrow"><span></span>Have a workflow in mind?</p><h2>Let’s turn it into a working advantage.</h2></div><a class="button button--light" href="<?php echo esc_url( home_url( '/contact/' ) ); ?>">Start the conversation <span>↗</span></a></div></section>
<?php get_footer(); ?>

