<?php get_header(); while(have_posts()): the_post(); $slug=get_post_field('post_name'); ?>
<section class="page-hero page-hero--compact"><div class="shell"><p class="eyebrow"><span></span>Legal</p><h1><?php the_title(); ?></h1><p>Last updated: <?php echo esc_html(wp_date('F j, Y')); ?></p></div></section>
<article class="section legal"><div class="shell legal__body">
<?php if ('privacy-policy'===$slug): ?><h2>1. Who we are</h2><p>MobileAI provides AI, automation and software consulting services from Croatia. Contact: <a href="mailto:hello@mobileai.hr">hello@mobileai.hr</a>.</p><h2>2. Information we collect</h2><p>We may collect contact details and the information you choose to send us, along with limited technical logs needed to keep this website secure and operational.</p><h2>3. Why we use it</h2><p>We process information to respond to enquiries, provide contracted services, meet legal obligations and protect our systems. Depending on the context, the legal basis is consent, contract, legal obligation or legitimate interest.</p><h2>4. Sharing and retention</h2><p>We only share data with service providers when needed to operate our business, under appropriate safeguards. We keep it no longer than necessary for its purpose and applicable law.</p><h2>5. Your rights</h2><p>Under the GDPR you may request access, correction, deletion, restriction, portability or object to certain processing. You may also complain to the Croatian Personal Data Protection Agency.</p><h2>6. Contact</h2><p>Send privacy requests to <a href="mailto:hello@mobileai.hr">hello@mobileai.hr</a>.</p>
<?php elseif ('cookie-policy'===$slug): ?><h2>1. About cookies</h2><p>Cookies are small files stored by your browser. This website is designed to operate with only essential cookies unless optional services are added later.</p><h2>2. Essential cookies</h2><p>WordPress may use cookies for authentication, security and user preferences. These are necessary when you sign in to the client portal and cannot be disabled through a consent tool.</p><h2>3. Optional cookies</h2><p>We do not intentionally set analytics or advertising cookies in this release. If this changes, we will update this policy and request consent where required.</p><h2>4. Browser controls</h2><p>You can delete or block cookies in your browser settings. Blocking essential cookies may prevent the client portal from working.</p><h2>5. Contact</h2><p>Questions can be sent to <a href="mailto:hello@mobileai.hr">hello@mobileai.hr</a>.</p>
<?php else: ?><h2>1. Scope</h2><p>These terms govern your use of this website. Separate written terms apply to paid services and client deliverables.</p><h2>2. Website information</h2><p>We aim to keep information accurate but provide website content for general information only. It is not professional, legal or financial advice.</p><h2>3. Intellectual property</h2><p>Unless stated otherwise, website text, design and original materials belong to MobileAI. You may not reproduce them commercially without permission.</p><h2>4. Acceptable use</h2><p>Do not misuse the website, attempt unauthorised access, interfere with availability or submit unlawful or harmful material.</p><h2>5. Third-party services</h2><p>Links and integrations may lead to third-party services governed by their own terms and privacy notices.</p><h2>6. Liability</h2><p>To the extent permitted by law, MobileAI is not liable for indirect loss arising solely from use of this public website.</p><h2>7. Governing law</h2><p>These terms are governed by Croatian law, without limiting mandatory consumer rights that may apply.</p><h2>8. Contact</h2><p>Questions can be sent to <a href="mailto:hello@mobileai.hr">hello@mobileai.hr</a>.</p><?php endif; ?>
<div class="legal-note"><strong>Launch note</strong><p>This baseline legal copy must be reviewed against the final business registration details, hosting, analytics, processors and commercial model before public launch.</p></div></div></article>
<?php endwhile; get_footer(); ?>

